# Site
name: IB Style
description: "楽しく、ラクに、プラスになるIB lifeを。"
meta_description: "「楽しく、ラクに、プラスになるIB lifeを。」をテーマに、IB生活に役立つ情報をお届けします!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
email: 'mail@ibstyle.tk'
google_analytics: 'UA-134828257-2'
disqus: 'ibstyle'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5c6cbaa79719b800115b64e4&product=sticky-share-buttons"></script>'

# Authors
authors:
  administrator:
    name: IB Style Official
    display_name: IB Style Official
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://ibstyle.tk/
    twitter: https://twitter.com/ibstyle_pr
    description: "IB Style公式アカウントです。"
  kyosuke.miyamura:
    name: Kyosuke
    display_name: Kyosuke
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  mei.kanda:
    name: May
    display_name: May
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/mkpanda_ibs
    twitter: https://twitter.com/mkpanda_ibs
    description: "IB Style リーダー兼ライター。日本語ネイティブ。7年生から玉川学園でIBを始め、10年生の時にGlenlyon Norfolk School (カナダ)に移る。HL: Math, Chemistry, Physics, English B SL: Geography, Japanese self-taught."
  shunsuke.nakayama:
    name: Shunsuke
    display_name: Shunsuke
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  koiki.kishi:
    name: Koiki
    display_name: Koiki
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  junya.eriguchi:
    name: Junya
    display_name: Junya
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  manami.fukushima:
    name: Manami
    display_name: Manami
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  miyu.osamura:
    name: Miyu
    display_name: Miyu
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/yooonmiyeon
    twitter: https://twitter.com/yooonmiyeon
    description: "IB Style ライター。5年生からアメリカ留学。その後日本に帰国し、8年生から同志社国際学院でIBを始める。11年生からカナダのGlenlyon Norfolk Schoolで卒業。"
  ami.okazaki:
    name: Ami
    display_name: Ami
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "玉川学園の幼稚部から通い、中学1年生の時IBコースに進学。DPではEconomics、Japanese (Literature)、Visual ArtのHLとEnglish (Language and Literature)、ESS、MathのSLを履修。2019年9月からボストン大学 芸術学部 舞台芸術学科に進学予定。"
  hiromi.egusa:
    name: Hiromi
    display_name: Hiromi
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://heyo7777.hatenablog.com/
    twitter: https://twitter.com/senegal_ib
    description: "準備中"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
permalink: '/posts/:slug/'
markdown: kramdown
highlighter: rouge
